### PR TITLE
Add PodcastIndexSharp to list of LIbraries

### PR DESCRIPTION
**Pull request by brb3**
Adds the `PodcastIndexSharp` library to the list of libraries.

This is a .NET Standard library for reading from the API.
The package repository is on gitlab at https://gitlab.com/brb3/podcastindexsharp.

### CODE REVIEW

**Comment by stevencrader** [comment]
If possible, can you run `yarn build` and commit the updated json and yaml file in docs? Those files need to be updated for this change to show at https://podcastindex-org.github.io/docs-api once merged.

I guess if you don't want to install node just to build them, the generated files could be updated manually.

**Comment by brb3** [comment]
Not a problem. I've added the generated yaml and json files to the PR.

**Comment by daveajones** [comment]
Thanks for this @brb3 !

**Comment by brb3** [comment]
Happy to help @daveajones -- I'll continue to expand on this library. I will be working on supporting the `/add/*` calls soon as well.

**Pull request merged**
